export const LABELS = {
  RU: {
    common_color_white: 'белый',
    common_color_black: 'чёрный',
    lose_screen_player_lose_title: 'игрок проиграл',
    lose_screen_play_again_button: 'Играть снова',
    lose_screen_back_to_menu_button: 'Назад к меню',
    watch_you_lose_message: 'Вы проиграли',
    settings_unnamed_button: 'без названия',
    settings_game_settings_title: 'Настройки игры',
    settings_game_time_title: 'Время на партию',
    settings_turn_limt_enable_title: 'Лимит на ход вкл.',
    settings_turn_limt_time_title: 'Лимит времени на ход',
    settings_turn_limt_extract_title: 'Вычитать из осн. времени',
    settings_language_title: 'Язык:',
    settings_language_russian: 'Русский',
    settings_language_english: 'Английский',
    settings_start_game_button: 'Начать игру',
  },
  EN: {
    common_color_white: 'white',
    common_color_black: 'black',
    lose_screen_player_lose_title: 'player lose',
    lose_screen_play_again_button: 'Play again',
    lose_screen_back_to_menu_button: 'Back to menu',
    watch_you_lose_message: 'You lose',
    settings_unnamed_button: 'unnamed button',
    settings_game_settings_title: 'Game settings',
    settings_game_time_title: 'Game time',
    settings_turn_limt_enable_title: 'Enable turn limit',
    settings_turn_limt_time_title: 'Turn limit time',
    settings_turn_limt_extract_title: 'Extract from game time',
    settings_language_title: 'Language:',
    settings_language_russian: 'Russian',
    settings_language_english: 'English',
    settings_start_game_button: 'Start Game',
  },
}